

PROJECT_NAME := lck-sesu

M_DEPS += ../../analogdevices/projects/adrv9361z7035/common/ccbob_constr.xdc
M_DEPS += ../../analogdevices/projects/adrv9361z7035/common/ccbob_bd.tcl
M_DEPS += ../../analogdevices/projects/adrv9361z7035/common/adrv9361z7035_constr_lvds.xdc
M_DEPS += ../../analogdevices/projects/adrv9361z7035/common/adrv9361z7035_constr.xdc
M_DEPS += ../../analogdevices/projects/adrv9361z7035/common/adrv9361z7035_bd.tcl

M_DEPS += ../../analogdevices/library/xilinx/common/ad_iobuf.v
M_DEPS += ../../analogdevices/library/axi_ad9361/axi_ad9361_delay.tcl

LIB_DEPS += axi_ad9361
LIB_DEPS += axi_dmac
LIB_DEPS += axi_gpreg
LIB_DEPS += axi_sysid
LIB_DEPS += sysid_rom
LIB_DEPS += util_pack/util_cpack2
LIB_DEPS += util_pack/util_upack2
LIB_DEPS += util_rfifo
LIB_DEPS += util_tdd_sync
LIB_DEPS += util_wfifo
LIB_DEPS += xilinx/axi_xcvrlb
LIB_DEPS += xilinx/util_clkdiv

include ../../analogdevices/projects/scripts/project-xilinx.mk

